import type {Metadata} from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "My Blog",
    description: "Generated by create next app",
};

export default async function RootLayout({children}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
            {/* 预加载字体 CSS */}
            <link
                rel="preload"
                href="/fonts/fonts.css"
                as="style"
            />
            <link
                rel="stylesheet"
                href="/fonts/fonts.css"
            />
        </head>
        <body>
        {children}
        </body>
        </html>
    );
}
