import type {Metadata} from "next";
import "./globals.css";
import Navbar from "@/app/components/navbar/Navbar";
import Footer from "@/app/components/Footer";
import getCurrentUser from "@/app/actions/getCurrentUser";
import {useSession} from "next-auth/react";

// 字体问题
// import {Nunito} from "next/font/google";
// const font = Nunito({
//     subsets: ['latin'],
// });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({children}: Readonly<{
    children: React.ReactNode;
}>) {
    const currentUser = await getCurrentUser()

    return (
        <html lang="en">
        <body className={"relative min-h-screen min-w-fit"}>
        <Navbar currentUser={currentUser}/>
        <div className={"pb-20 pt-28"}>
            {children}
        </div>
        <Footer/>
        </body>
        </html>
    );
}
