import type {Metadata} from "next";
// import "./globals.css";
import Navbar from "@/app/components/navbar/Navbar";
import Footer from "@/app/components/Footer";
import getCurrentUser from "@/app/actions/getCurrentUser";

// 字体问题
// import {Nunito} from "next/font/google";
// const font = Nunito({
//     subsets: ['latin'],
// });
// <main className={"pb-20 pt-24 md:pt-28 px-10"}>

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({children}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className={"pt-28 px-10"}>
            {children}
        </div>
    );
}
